services:
  - type: web
    name: stock-screening-app
    runtime: docker
    repo: https://github.com/jun4696/stock_screening_app.git
    branch: master
    plan: free
    region: singapore
    healthCheckPath: /_stcore/health
    autoDeployTrigger: commit
    envVars:
      - key: EDINETDB_API_KEY
        sync: false
      - key: JQUANTS_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TZ
        value: Asia/Tokyo
